### ISSUE TITLE
Checklist for v1

### ISSUE THREAD

**Issue by kiko-g** [kiko-g/bagger-flow-vscode#1]
- [x] Increase alpha value in active tabs
- [x] Increase alpha value when hovering tabs
- [x] Select text icy color
- [x] Find match colors
- [x] Reconfigure terminal colors
- [x] Welcome page color
- [ ] Git merge conflicts colors
